/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IItemThumbnailArgs {
    thumbnail_absolute_path?: string;
}
export class ItemThumbnail {
    public thumbnail_absolute_path?: string;
    constructor(args?: IItemThumbnailArgs) {
        if (args != null && args.thumbnail_absolute_path != null) {
            this.thumbnail_absolute_path = args.thumbnail_absolute_path;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ItemThumbnail");
        if (this.thumbnail_absolute_path != null) {
            output.writeFieldBegin("thumbnail_absolute_path", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.thumbnail_absolute_path);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ItemThumbnail {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.thumbnail_absolute_path = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ItemThumbnail(_args);
    }
}
